"use client";

import { Brain, Sparkles } from "lucide-react";
import { Button } from "@/components/shared/Button";
import { useAIStore } from "@/store/ai_store";

export function AISummaryPanel({ meetingId }: { meetingId: number }) {
  const { summary, processing, error, generateSummary } = useAIStore();
  const summaryBlocks = summary?.generated_summary.split(/\n+/).filter(Boolean) ?? [];

  return (
    <section className="panel p-5">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h2 className="flex items-center gap-2 text-base font-semibold text-slate-950">
            <Brain className="h-5 w-5 text-zoom-blue" aria-hidden="true" />
            AI meeting summary
          </h2>
          <p className="mt-1 text-sm text-slate-500">Generated recap, highlights, and decision context.</p>
        </div>
        <Button
          type="button"
          variant="secondary"
          disabled={processing}
          onClick={() => void generateSummary(meetingId)}
          icon={<Sparkles className="h-4 w-4" aria-hidden="true" />}
        >
          {processing ? "Generating..." : "Generate"}
        </Button>
      </div>

      <div className="mt-4 space-y-3 rounded-lg border border-blue-100 bg-blue-50/60 p-4">
        {summaryBlocks.length > 0 ? (
          summaryBlocks.map((block, index) => (
            <div key={block} className="rounded-md bg-white/70 p-3">
              <p className="text-xs font-semibold uppercase text-blue-700">
                {index === 0 ? "Recap" : index === 1 ? "Key signals" : "Follow-up"}
              </p>
              <p className="mt-1 text-sm leading-6 text-slate-700">{block}</p>
            </div>
          ))
        ) : (
          <p className="text-sm leading-6 text-slate-700">
            Submit a transcript or use an existing transcript to generate a persisted meeting recap.
          </p>
        )}
      </div>
      {summary && (
        <p className="mt-3 text-xs text-slate-500">
          Generated by {summary.generated_by_model} | {new Date(summary.created_at).toLocaleString()}
        </p>
      )}
      {error && <p className="mt-3 text-sm text-red-600">{error}</p>}
    </section>
  );
}
